### ISSUE TITLE
Experimenting with UI?

### ISSUE THREAD

**Issue by aegershman** [thomasmmitchell/doomsday#7]
I'd like to experiment with the UI, but it doesn't appear to be "active" out of the box. It appears the UI is only available if you turn on the ability to server from the `web/` folder via these config params:

```
server:
  dev:
    mappings:
      web/index.html: "index.html"
      web/lens.js: "web/assets/lens.js"
      web/stylesheet.css: "web/assets/stylesheet.css"
```

but I'm not sure if this is totally correct?

Regardless, how would I turn on the UI?

Thanks so much. I just found out about this project and think it's fantastic.

**Comment by thomasmitchell** [comment]
The UI hasn't quite been released yet is all. I'm still finishing up the auth stuff in the UI. Once it's done, I'll be cutting a release where the UI is embedded into the binary and it will be on by default. If you wanted to custom build it and turn on the WIP UI, then I use this in my dev config.
```
server:
 dev:
   mappings:
     web/index.html: /
     web/stylesheet.css: web/assets/stylesheet.css
     web/lens.js: web/assets/lens.js
```

I'm hoping to have the release with the UI actually in it out early next week.
